### ISSUE TITLE
Lost ability to browse stations

### ISSUE THREAD

**Issue by Justin321** [kingosticks/mopidy-tunein#19]
After performing a 'mopidy local clear' & 'mopidy local scan' lost the ability to browse TuneIn stations.  Tried uninstalling and installing mopidy-tunein but browse only shows "Trending" under Directories/Files

Metadata-Version: 1.1
Name: Mopidy-TuneIn
Version: 0.2.2

**Comment by adamcik** [comment]
This is likely not related to local as the two extensions have nothing to do with each other. 

See https://docs.mopidy.com/en/latest/troubleshooting/ - specifically ``mopidy --save-debug-log`` or an equivalent and then please provide it in a pastebin so we have more to go on :-)

**Comment by kingosticks** [comment]
I think you'd get that if the tunein service was down or if you'd somehow
managed to do a lookup on everything, in which case you'd exceed tunein's
rate limit and be temporarily banned/throttled. Don't see how those two
commands would do that, as @adamcik says, local is totally separate.

**Comment by Justin321** [comment]
Thanks - Problem seems intermittent so will play around with debugging when
I can.  Added Dirble which works well with the Radio stations I was looking
for and seems more reliable.

**Comment by kingosticks** [comment]
Please reopen if there is anything to do here for Tunein.
