### ISSUE TITLE
Error "The stream is of a different type than handled by this element." for some radio streams

### ISSUE THREAD

**Issue by ttheuer** [kingosticks/mopidy-tunein#23]
When trying to play some radio streams on my RPi running Raspbian Jessie I get the following error message:
`ERROR The stream is of a different type than handled by this element.`

This happens reproducibly with all Digitially Imported streams, e.g. Music > Ambient > [DI] Ambient

The AudioAddict plugin used to have the same error, but they patched it somehow:
https://github.com/nilicule/mopidy-audioaddict/issues/6

**Comment by ttheuer** [comment]
I hate to be a nuisance, but for someone who knows what they're doing this should be fixable, surely.
I'd love to get some feedback here.

**Comment by kingosticks** [comment]
https://github.com/kingosticks/mopidy-tunein/pull/21.

I still don't know what is the best plan here. The Tunein class has a bunch of hacks for supporting badly formatted playlists which Mopidy doesn't. I guess not supporting crappy playlists is better than not supporting all playlists....
