### ISSUE TITLE
Network Ports

### ISSUE THREAD

**Issue by JayBeeDe** [kingosticks/mopidy-tunein#29]
Hi,

I have installed Tunein and it sounds to be really great. Hope authentication is coming soon!

**Which networks ports are used to communicate to outside (I mean the tunein service)? Which protocol is used? TCP/UDP?**

I have tried netstat but I didn't find something related to tunein. In fact, I will restrict ports with iptables, but I don't want to block ports used by this extension...

**Comment by kingosticks** [comment]
Most mopidy extensions just do standard http requests, nothing fancy. 

I've no plans to implement authentication unless tunein provide public documentation.
