### ISSUE TITLE
Stream not compatible

### ISSUE THREAD

**Issue by fmarzocca** [kingosticks/mopidy-tunein#53]
There are a couple of radio stations in TuneIn that I’d like to play on mopidy, but when I connect to them, TuneIn answers with a voice saying: “_This stream is not compatible with this player_”. (i.e. `tunein:station:s6535`)

Is there any enhancement I can do to listen to those radios?

Thanks

**Comment by kingosticks** [comment]
Not that I know. You could enable verbose logging and see if there are any more hints to why they've decided that.

**Comment by fmarzocca** [comment]
Hi, thanks for your reply.
This is what I found in the log, enabling DEBUG on mopidy_tunein:

```
Apr 20 11:57:53 pab mopidy[1196]: DEBUG    [TuneInBackend-7] mopidy_tunein.tunein Fetching info for station s6535
Apr 20 11:57:53 pab mopidy[1196]: DEBUG    [TuneInBackend-7] mopidy_tunein.tunein TuneIn request: 'https://opml.radiotime.com/Describe.ashx?render=json&c=composite&detail=listing&id=s6535'
Apr 20 11:57:54 pab mopidy[1196]: DEBUG    [TuneInBackend-7] mopidy_tunein.tunein Tuning station id s6535
Apr 20 11:57:54 pab mopidy[1196]: DEBUG    [TuneInBackend-7] mopidy_tunein.tunein TuneIn request: 'https://opml.radiotime.com/Tune.ashx?render=json&id=s6535'
Apr 20 11:57:54 pab mopidy[1196]: DEBUG    [TuneInBackend-7] mopidy_tunein.actor Looking up URI: 'http://cdn-cms.tunein.com/service/Audio/notcompatible.enUS.mp3'
Apr 20 11:57:54 pab mopidy[1196]: DEBUG    [TuneInBackend-7] mopidy_tunein.actor Unwrapping stream from URI: 'http://cdn-cms.tunein.com/service/Audio/notcompatible.enUS.mp3'
Apr 20 11:57:54 pab mopidy[1196]: DEBUG    [TuneInBackend-7] mopidy_tunein.actor Unwrapped potential None stream: 'http://cdn-cms.tunein.com/service/Audio/notcompatible.enUS.mp3'
Apr 20 11:58:25 pab mopidy[1196]: DEBUG    [TuneInBackend-7] mopidy_tunein.tunein Tuning station id s6535
Apr 20 11:58:25 pab mopidy[1196]: DEBUG    [TuneInBackend-7] mopidy_tunein.actor Looking up URI: 'http://cdn-cms.tunein.com/service/Audio/notcompatible.enUS.mp3'
Apr 20 11:58:25 pab mopidy[1196]: DEBUG    [TuneInBackend-7] mopidy_tunein.actor Unwrapping stream from URI: 'http://cdn-cms.tunein.com/service/Audio/notcompatible.enUS.mp3'
Apr 20 11:58:25 pab mopidy[1196]: DEBUG    [TuneInBackend-7] mopidy_tunein.actor Unwrapped potential None stream: 'http://cdn-cms.tunein.com/service/Audio/notcompatible.enUS.mp3'
Apr 20 11:58:33 pab mopidy[1196]: DEBUG    [TuneInBackend-7] mopidy_tunein.tunein Tuning station id s6535
Apr 20 11:58:33 pab mopidy[1196]: DEBUG    [TuneInBackend-7] mopidy_tunein.actor Looking up URI: 'http://cdn-cms.tunein.com/service/Audio/notcompatible.enUS.mp3'
Apr 20 11:58:33 pab mopidy[1196]: DEBUG    [TuneInBackend-7] mopidy_tunein.actor Unwrapping stream from URI: 'http://cdn-cms.tunein.com/service/Audio/notcompatible.enUS.mp3'
Apr 20 11:58:33 pab mopidy[1196]: DEBUG    [TuneInBackend-7] mopidy_tunein.actor Unwrapped potential None stream: 'http://cdn-cms.tunein.com/service/Audio/notcompatible.enUS.mp3'
```

**Comment by kingosticks** [comment]
I guess not. Your guess is as good as mine how to play a stream like this, it seems to work a different way to the others.

**Comment by kingosticks** [comment]
Note, this stream is also unplayable in some regions (e.g. mine).

**Comment by fmarzocca** [comment]
> I guess not. Your guess is as good as mine how to play a stream like this, it seems to work a different way to the others.

But it plays on TuneIn web page. https://tunein.com/radio/Radio-Capital-955-s6535/

**Comment by fmarzocca** [comment]
> Note, this stream is also unplayable in some regions (e.g. mine).

I guess it is not a matter of "region". It doesn't play from mopidy's player.

**Comment by kingosticks** [comment]
The stream is region locked for me. I know this because that's what it says on the TuneIn web page when I visit it on my PC from my location. 

Presumably you are in the correct region so there's some other problem going on - hence "it seems to work a different way to the others". I don't know how the TuneIn web player works but clearly it supports that other way.

I hope that is clearer.

**Comment by kingosticks** [comment]
If you can work out how to make it work, please re-open, provide the steps and we'll implement it. Otherwise there's just no solution for a stream like this

**Comment by fmarzocca** [comment]
Ok.
For the time being, I have found another stream for that radio, which is compatible:
https://4c4b867c89244861ac216426883d1ad0.msvdn.net/radiocapital/radiocapital/play1.m3u8

Added to playlist.
